name: flutteruitest
description: purred ui test

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc:
  http:
  equatable:
  carousel_slider: ^1.3.1
  rxdart: ^0.24.1
  provider: ^4.1.2
  cupertino_icons: ^0.1.3
  lottie: ^0.4.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - assets/
  - images/
